### ISSUE TITLE
[ENH] `pyrosm.OSM.to_graph` has a misleading name

### ISSUE THREAD

**Issue by christophfink** [HTenkanen/pyrosm#134]
Going along with the conventions set forward by, e.g., pandas, methods of data classes/objects that follow the form `to_${format}` export the local object’s data to `${format}`. 

`pyrosm.OSM.to_graph()` is more of a static method, and would be better called something along the lines of `graph_from_nodes_and_edges()`. 

It is a rather trivial change, but potentially breaks derived works. Still, it seems like a as-soon-as-possible-or-never thing to change to follow common conventions.

**Comment by HTenkanen** [comment]
> How about network_to_graph, or graph_from_network?

Graph and network are synonyms, so this is a bit ambiguous as well 🙂 (which one is used depends on the discipline). I think `graph_from_nodes_and_edges()` is the most unambiguous name to use but as said it's quite chunky, and because it is used very often by pyrosm users who continue working with network analysis libraries, it would mean repeating that long name time after another... 😄 

> please make it a @staticmethod, since it’s not using anything related to the class or instances.

Yes, this is something that should be changed 👍🏻
