### ISSUE TITLE
Potential memory issue when using `get_boundaries`

### ISSUE THREAD

**Issue by Zigur** [HTenkanen/pyrosm#152]
Hello, I did try to use one of your examples to get the county boundaries of Great Britain

```
COUNTRY = "Great Britain"


def main() -> None:

    print("This is my main()")
    fp = get_data(COUNTRY)
    osm = OSM(fp)

    boundaries = osm.get_boundaries()
    boundaries.plot(facecolor=None, edgecolor="gray")
```

When the execution reaches `osm.get_boundaries()` it hangs for a while and then it crashes with this error message:

```
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

Which could be caused by an insufficient memory issue. Running this on an Ubuntu 20.04 machine, using a python 3.9.7 virtual environment.
Has anyone encountered this issue?
Thanks a lot for the help.

**Comment by HTenkanen** [comment]
@Zigur With the current logic of pyrosm, trying to parse data covering whole GB is not possible because (all) the data from PBF is read into memory. In the future release, the goal is to change this logic so that you can read data from large PBF files (basically the size of the disk is then the limit)

**Comment by Zigur** [comment]
Thanks for the clarification @HTenkanen. So if I want to get the county boundaries a sensible way would be to iterate through all the counties and get each boundary, right? Giving it a try.

**Comment by Zigur** [comment]
Sorry to pester you again, maybe it's not even a pyrosm related issue.

If I get the boundaries of an English county and plot them, there are some weird straight lines that do not belong to administrative divisions.

For instance, if I plot the Oxfordshire map:
```
fp = get_data("oxfordshire")
osm = OSM(fp)
boundaries = osm.get_boundaries()
boundaries.plot(
    facecolor="none",
    edgecolor="gray",
    figsize=(8, 8)
)
```
I get this map with some straight random lines:

![image](https://user-images.githubusercontent.com/6864177/141335723-9f7e21d4-7cfa-4d5a-9391-47a525293e71.png)

Getting only the border named "Oxfordshire" from the administrative_level corresponding to counties does not help either.

```
oxon_boundaries = osm.get_boundaries(name="Oxfordshire")
oxon_boundaries = oxon_boundaries[oxon_boundaries.admin_level == '6']
oxon_boundaries.plot(facecolor="none", edgecolor="gray")
```

![image](https://user-images.githubusercontent.com/6864177/141336359-8e9adafa-25a4-4543-a89b-88a3cd771b0d.png)

Should I filter some of the boundaries out?

**Comment by HTenkanen** [comment]
@Zigur Thanks for reporting this! 🙏🏻 Definitely this is something that should not happen. Could you open a new issue for this, so I'll check what causes this behavior. The most likely reason for this relates to how the geometries are parsed and when "closing" the linear ring. This is a good test case for debugging the issue because you seem to have so many problematic geometries.

**Comment by Zigur** [comment]
sure

**Comment by acmeguy** [comment]
This is still happening for me. Is this solved?
