### ISSUE TITLE
TypeError: get_data_by_custom_criteria() got an unexpected keyword argument 'timestamp'

### ISSUE THREAD

**Issue by wendy-ngan** [HTenkanen/pyrosm#157]
I want to download geofabrik canada files from their raw directory index with public transit filter. I tried the following and got a type error for timestamp:

```
from pyrosm import OSM
from pyrosm import get_data

osm = OSM(get_data("canada"))

routes = ["bus", "ferry", "railway", "subway", "train", "tram", "trolleybus"]
rails = ["tramway", "light_rail", "rail", "subway", "tram"]
bus = ['yes']
transit = osm.get_data_by_custom_criteria(custom_filter={
                                        'route': routes,
                                        'railway': rails,
                                        'bus': bus,
                                        'public_transport': True},
                                        # Keep data matching the criteria above
                                        filter_type="keep",   
                                        timestamp="2017-01-01")
```

**Comment by HTenkanen** [comment]
@wendy-ngan :  The `timestamp` parameter is currently only available in the development version of the pyrosm that should be installed from the master branch (hence you should just not specify the `timestamp` at all).  

Other thing relating to your question: `pyrosm`  isn't yet capable of handling data files as big as whole Canada which is 2.6 GB in size. Hence, it is very unlikely that your query would finish successfully because there is not enough memory (RAM) to finish the task.
