### ISSUE TITLE
`addr:suburb` from osm.pbf

### ISSUE THREAD

**Issue by AdrianKriger** [HTenkanen/pyrosm#167]
Hi.
Thank you for this library. 

Why does the osm.pbf harvested via pyrosm not have the `addr:suburb` tags?
```python

from pyrosm import OSM, data
from pyrosm import get_data
import geopandas as gpd

fp = get_data("CapeTown", update=False, directory="data")
osm = OSM(fp)
aoi = osm.get_boundaries(name='Cape Town Ward 57')
# Get the shapely geometry from GeoDataFrame
bbox_geom = aoi['geometry'].values[0]
# Initiliaze with bounding box
osm = OSM(fp, bounding_box=bbox_geom)
# Retrieve buildings
ts = osm.get_buildings()
ts.head(2)
```
produces:
```addr:city   addr:country   addr:housenumber   addr:housename   addr:postcode   addr:place   addr:street   email	name  etc.```

with [overpass](https://overpass-turbo.eu/#)
```
[out:json][timeout:30];
// --when areas have duplicate names given the world has a limited amount of uniquely named places
(area[name='Western Cape'] ->.b;
    // -- target area ~ can be way or relation
    relation(area.b)[name='Cape Town Ward 57'];
    map_to_area -> .a;
        // I want all buildings
        way['building'](area.a);
        // and relation type=multipolygon ~ to removed courtyards from buildings
        relation["building"]["type"="multipolygon"](area.a);
    );
out body;
>;
out skel qt;
```
produces -> random example:
```
...
"tags": {
    "addr:city": "Cape Town",
    "addr:housenumber": "9",
    "addr:postcode": "7915",
    "addr:street": "Roodebloem Road",
    "addr:suburb": "Woodstock",
    "building": "house",
    "building:levels": "1"
  }
...
```

**Comment by HTenkanen** [comment]
@AdrianKriger Hi! Thanks for reaching out! 

`pyrosm` works in a bit different way as overpass, because the end result of pyrosm is a columnar geopandas GeoDataFrame. To avoid generating a separate column for all possible OSM keys (which are numerous), we have limited the OSM keys that are returned as columns by default. However, all the "none-deafault" attributes are stored in `tags` column as a JSON string from where you should be to see the value e.g. for `addr:suburb` for given element. 

In case you want to extract a specific attribute as a column (that is not returned by default), you can do this easily by using the `extra_attributes` parameter that is available for all pyrosm functions. Read more from the documentation: https://pyrosm.readthedocs.io/en/latest/basics.html#controlling-which-osm-attributes-are-parsed-into-columns

**Comment by AdrianKriger** [comment]
```python
blds = osm.get_buildings(extra_attributes=["addr:suburb"])
``` 
did the business. Thank you

**Comment by HTenkanen** [comment]
Great! 👍🏻 Closing this now.

**Comment by AdrianKriger** [comment]
Does that mean: `aoi = osm.get_boundaries(extra_attributes=["boundary:place"])` would similarly harvest the boundary `key:value` pair that is not shown by default @HTenkanen?
