### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by Giacomo8899** [HTenkanen/pyrosm#210]
**Describe the bug**
AttributeError: module 'numpy' has no attribute 'float'

**To Reproduce**

# the code is 

from pyrosm import OSM
from pyrosm import get_data
osm = OSM('provence-alpes-cote-d-azur-latest.osm.pbf')
buildings = osm.get_buildings()

the file was dowloaded here
https://download.geofabrik.de/europe/france.html

**Expected behavior**
extract the buildings

**Environment:**
 - OS: Window
 - Python package source: miniconda

**Comment by Giacomo8899** [comment]
The error arise in the file geometry.pyx:312, in pyrosm.geometry.create_linestring_geometry()

**Comment by lukasbeuster** [comment]
This is likely due to your numpy version.

"As of numpy v1.20, numpy.float as well as similar aliases (including numpy.int) were deprecated." Finally: 

"Going forward, numpy v1.24.0 has removed these aliases completely and this is the reason why we’re seeing this error whenever such aliases are used."
[](https://levelup.gitconnected.com/fix-attributeerror-module-numpy-has-no-attribute-float-d7d68c5a4971)

So check if your numpy is >1.24.0, and if it is downgrade to an earlier version.

Downgrading to 1.23.5 works, this can be done e.g., by using `conda install -c conda-forge numpy=1.23.5 `

**Comment by Giacomo8899** [comment]
Thanks!

**Comment by miettal** [comment]
@HTenkanen This problem already been fixed in master branch. But this changing is not released yet.
Do you have release planning?

**Comment by geomUm** [comment]
import numpy as np

np.float = float

works for me

**Comment by HTenkanen** [comment]
This is now fixed in the new release pyrosm v0.6.2 which fixes the numpy related issues. See #214
