### ISSUE TITLE
Filters on highway is and, others are or ?

### ISSUE THREAD

**Issue by chourmo** [HTenkanen/pyrosm#22]
Thanks for this great project.

The boolean logic of filters seems to be a "or" on each key, except on "highway"
 {
    "cycleway": ["yes", "track", "opposite_track", "share_busway", "shared", "lane", "opposite_lane", "opposite", "shared_lane", "opposite_share_busway"],
    "cycleway:left": ["lane", "yes"],
    "cycleway:right": ["lane", "yes"],
    "cycleway:both": ["lane", "yes"],
    "bicycle": ["designated", "shared", "yes"],
}

gives 11410 on my dataset provence-alpes-cote-d-azur-latest.osm.pbf
while 
{
    "cycleway": ["yes", "track", "opposite_track", "share_busway", "shared", "lane", "opposite_lane", "opposite", "shared_lane", "opposite_share_busway"],
    "cycleway:left": ["lane", "yes"],
    "cycleway:right": ["lane", "yes"],
    "cycleway:both": ["lane", "yes"],
    "highway": ["cycleway"],
    "bicycle": ["designated", "shared", "yes"],
} 
gives 1825 rows.

Is highway considered a "and" during filtering ?

If so, could it be optional or at least documented ?

**Comment by HTenkanen** [comment]
@chourmo Thanks for your feedback! When doing these calls, are you using the `get_data_by_custom_criteria()` method? Could you explain shortly what you are trying to do, so I can help you out to create a correct kind of filter.

The way how filtering the roads is done by default in `get_network()` is by **excluding** data (i.e. dropping out) if certain tags are found from the data (see e.g. [this example](https://github.com/HTenkanen/pyrosm/blob/master/pyrosm/config/osm_filters.py#L81)). I believe that in here you are creating a filter which does this other way around, i.e. using `filter_type="keep"` (which is the default behavior, the other option is `filter_type="exclude"`). 

The reason why you get so much fewer roads on the last call, is because there is this additional check that `highway` tag should be `"cycleway"` (and nothing else is accepted) whereas in the first one there is no filtering criteria for "highway" tag at all. Hence, it is natural that you get much more rows with the first filter.

**Comment by HTenkanen** [comment]
@chourmo Okay, I checked the things now using your data, and it seems that the filtering with "keep" does not work as it should, as there are rows "leaking" to the final results even when the criteria in the custom_filter (i.e. "second-level filtering") is not met, as in this example where I applied your filtering criteria:
![image](https://user-images.githubusercontent.com/6659534/80380465-87eb3780-8897-11ea-83f3-b477a1f3e705.png)

Thanks for reporting! I will look into this. 👍

**Comment by HTenkanen** [comment]
TODO (issue): When **none** of the filter keys exist for a given OSM element, it should be dropped out. Otherwise additional rows *leak* to the result after filtering.

**Comment by HTenkanen** [comment]
@chourmo Okay, now the new version of Pyrosm (v.0.4.3) should filter the data correctly and e.g. with the filters and data that you shared will produce something like:
![image](https://user-images.githubusercontent.com/6659534/80388712-1e245b00-88a2-11ea-8c8d-73207914e977.png)

If there is still something else that seems to be incorrect, feel free to reopen this issue, or open a new one. Otherwise, updating the library to the new version fixes the issues related to filtering.
