### ISSUE TITLE
Map Dubai or United Arab Emirates not available in data source 

### ISSUE THREAD

**Issue by Rahulvks** [HTenkanen/pyrosm#31]
Dear Team,
Thanks for the wonderful tool. Map Dubai or the United Arab Emirates not available in the data source kindly let me know how can use UAE data?

**Comment by HTenkanen** [comment]
Dear @Rahulvks,

and thanks for getting in touch. I think those should be available in `"gcc_states"`:
http://download.geofabrik.de/asia/gcc-states.html

The tool follows the data structure defined by Geofabrik, so that's why this works like this. 

Could you test this and if it does not work, don't hesitate to come back to this. :slightly_smiling_face:

**Comment by HTenkanen** [comment]
Also other possibility is to use this tool by Bbbike, if you wan't to get data from a smaller area (such as Dubai) : https://extract.bbbike.org/

**Comment by Rahulvks** [comment]
Thanks, @HTenkanen  let me try and get back.

**Comment by HTenkanen** [comment]
@Rahulvks , I assume you were able to download the data for Dubai, and will close this issue. If you still have issues, feel free to re-open this issue or raise a new one! 🙂
