### ISSUE TITLE
setup.py install of Cython and cykhash breaks in some contexts

### ISSUE THREAD

**Issue by geoDavey** [HTenkanen/pyrosm#38]
Hey! Really neat package! Will love to be a part & contribute.

I've had an adventure to get the module to install with pipenv. First, the module was trying to install with python2.7 because setup.py is executed with `/usr/bin/env python` which for me (and on many systems) resolves to python2, and same with pip resolving to pip2. I've made a pull request to fix these issues #37 and make installation with python3 more explicit.

The install of Cython and cykhash is indeed a hacky way (as suggested by the comments in file) and I'm super keen to help find a way to make these dependencies resolve more organically. In particular, the explicit installing of these modules via pip doesn't play well with virtual environments/pipenv.

Any ideas on how to make the dependencies resolve in a more self-contained & reproducible manner?

**Comment by HTenkanen** [comment]
Hi @geoDavey! And thanks for your help, and definitely it would be awesome if you'd be willing to help and contribute to this library! 👍  

Indeed, the pip installation is currently a bit hacky as mentioned.. I am at the moment pushing to release pyrosm in conda-forge which would make the installation procedure much more stable/secure using conda, but I think also improving the basic pip installation would be good. Currently the limitation for releasing pyrosm on conda-forge is that Cykhash (one of the dependencies) wasn't published on conda-forge but this should be resolved soon (see [here](https://github.com/conda-forge/staged-recipes/pull/11946))

For resolving the current dependencies (Cython, OSMPBF/Pyrobuf and Cykhash), I think it might be good to take a look how other Cython dependent libraries are being installed/built, such as [pandas](https://github.com/pandas-dev/pandas/blob/master/setup.py) and [Cykhash](https://github.com/realead/cykhash/blob/master/setup.py). If you want to explore those, I'd be happy to take a PR in. 🙂 

I'll comment separately on your PR #37.

**Comment by HTenkanen** [comment]
@geoDavey Hmm, I am not too familiar with pipenv, but it seems to be another package manager somewhat similar to [conda](https://docs.conda.io/en/latest/). Do you know if there are any specific reasons to use pipenv instead of conda? I'm just thinking whether it makes sense to start mixing these two package managers together as it seems that pipenv has some own tricks how things should be done..

**Comment by HTenkanen** [comment]
@geoDavey Okay `pyrosm` is now available from conda. See #39. I would recommend you to take a look at [conda](https://docs.conda.io/en/latest/) and perhaps migrate using that as your package manager instead of pipenv as it works better with compiled code (such as Pyrosm with Cython). Here's some more information: https://towardsdatascience.com/guide-of-choosing-package-management-tool-for-data-science-project-809a093efd46

In terms of improving the `pip` installation (removing the "hackish" steps from setup.py), I think using `pyproject.toml` and uploading the package to PyPi with [Flit](https://flit.readthedocs.io/en/latest/index.html) would be an optimal solution as that seems to be the future of [Python packaging (PEP 518)](https://snarky.ca/what-the-heck-is-pyproject-toml/). Unfortunately, Flit does not seem to support Cython yet, so this does not really work for pyrosm.

**Comment by HTenkanen** [comment]
Okay [Poetry](https://python-poetry.org/) seems to be a good solution for handling the packaging, short intro: https://hackersandslackers.com/python-poetry-package-manager/

**Comment by HTenkanen** [comment]
Now also the pip installation is more "clean" and follows PEP 518 style. 

Closing this now as the issues here has been resolved:
 - In terms of `pipenv` --> please consider using conda for managing your packages. 
 - pip installation was made clean. See #40 for details.

@geoDavey Sorry for not waiting for your replies, but I now had a bit of time to proceed with these, so did not want to wait. Very happy to take in future PRs / issues from you, if you find something to improve or have ideas for new features.
