### ISSUE TITLE
Feature request: optionally, return a node geodataframe from osm.get_network()

### ISSUE THREAD

**Issue by CWen001** [HTenkanen/pyrosm#52]
Thank you very much for the package. Downloading first from Geofabrik and then parsing a network is much faster than doing it in `osmnx`. 

However, a common use case for `pyrosm` is to extract a network and then to analyze it in `osmnx`. For that, Constructing a graph from geodataframe using `osmnx` is necessary, by `osmnx.graph_from_gdfs()`. 

Signature: `osmnx.graph_from_gdfs(gdf_nodes, gdf_edges, graph_attrs=None)`

    Parameters
    ----------
    gdf_nodes : geopandas.GeoDataFrame
        GeoDataFrame of graph nodes
    gdf_edges : geopandas.GeoDataFrame
        GeoDataFrame of graph edges, must have crs attribute set
    graph_attrs : dict
        the new G.graph attribute dict; if None, add crs as the only
        graph-level attribute

    Returns
    -------
    G : networkx.MultiDiGraph
    """

Currently, `osm.get_network()` only returns an edge gdf. Is is possible to also a node gdf? Thanks.

**Comment by HTenkanen** [comment]
Hi @CWen001 and thanks for your request! And sorry for only now coming back to this. 

So basically if I understand you correctly, you would like to be able to convert the network from pyrosm into a networkx graph, so that you are able to conduct further analyses using networkx? Are there some specific functionalities from `osmnx` that you would need specifically? The reason I am asking is because it is more straightforward to convert the data directly into NetworkX object.

**Comment by CWen001** [comment]
Thanks for the reply. Yes, I'd like to use `osmnx` to draw an isochrone map and measure some indicators (e.g. centrality), as shown in its [tutorial notebooks](https://github.com/gboeing/osmnx-examples/tree/master/notebooks). Another reason for requesting an optional node geodataframe is that, besides constructing an `osmnx` objectt, using `pandana` to calculate large-scaled distance matrix also requires both edges and node inputs to build its internal graph.

**Comment by HTenkanen** [comment]
@CWen001 Thanks for your input! 👍 I will add the possibility to fetch also the associated nodes when retrieving the network. I will most likely add an optional parameter `keep_nodes=False` that you can switch to `True` in order to retrieve both edges and nodes. 

FYI: It is already now possible to fetch **all** nodes of the given PBF as a GeoDataFrame via `osm._nodes_gdf` but this is not very useful as most of the nodes are related to something else than the street network.

**Comment by CWen001** [comment]
@HTenkanen Thank you very much for your excellent work! I'm looking forward to the new release.
