### ISSUE TITLE
QUESTION: custom filter Bug

### ISSUE THREAD

**Issue by der-karl** [HTenkanen/pyrosm#62]
I want to filter out all values from `'waterway'` tag, except for `'river'` and `'stream'`.
Using `filter_type='exclude'` will get the desired values but also other values from `'waterway'`, which should be filtered out (if I don't misunderstand). And `filter_type='keep'` works fine in this case. Why?

```
from pyrosm import OSM, get_data
import time


fp = get_data('helsinki')
osm = OSM(fp)

# Show all tags that are converted into columns from waterway features
waterways = osm.conf.tags.waterway

# Using filter_type='exclude'
waterways_exclude = waterways
waterways_exclude.remove('river')
waterways_exclude.remove('stream')

# Parse lines and time it
start_time = time.time()
my_waterways = osm.get_data_by_custom_criteria(custom_filter={
    'waterway': waterways_exclude},
    filter_type='exclude',
    keep_nodes=False,
    keep_ways=True,
    keep_relations=True)
print(f"Parsing lines lasted {round(time.time() - start_time, 0)} seconds.")
print(f"Number of lines parsed: {len(my_waterways)}")

# Count the number of each waterway type
type_waterways = my_waterways.groupby('waterway')
print(type_waterways.count())

# Parsing lines lasted 13.0 seconds.
# Number of lines parsed: 3775
#                 id  timestamp  version  tags  geometry  osm_type  changeset
# waterway                                                                   
# brook           72         72       72    30        72        72          0
# construction     6          6        6     6         6         6          0
# fish_pass        1          1        1     0         1         1          0
# flood_path       1          1        1     0         1         1          0
# proposed         1          1        1     1         1         1          0
# river           39         39       39    37        39        39          1
# ster             1          1        1     0         1         1          0
# stream        3654       3654     3654  2195      3654      3654          2

# Using filter_type='keep'
waterways_keep = ['river', 'stream']

start_time = time.time()
my_waterways = osm.get_data_by_custom_criteria(custom_filter={
    'waterway': waterways_keep},
    filter_type='keep',
    keep_nodes=False,
    keep_ways=True,
    keep_relations=True)
print(f"Parsing lines lasted {round(time.time() - start_time, 0)} seconds.")
print(f"Number of lines parsed: {len(my_waterways)}")

type_waterways = my_waterways.groupby('waterway')
print(type_waterways.count())

# Parsing lines lasted 1.0 seconds.
# Number of lines parsed: 3693
#             id  timestamp  version  tags  geometry  osm_type  changeset
# waterway                                                               
# river       39         39       39    37        39        39          1
# stream    3654       3654     3654  2195      3654      3654          2
```

**Comment by HTenkanen** [comment]
@der-karl Hi! Thanks for the question.

I went through your code snippet (thanks for this very good reproducible issue! 💯). And based on your description everything seems to work as should. 

In your first case with "exclude" keyword every record where the tag in "waterways" is **not** mentioned in the `waterways_exclude` list is kept. Hence, e.g. the "river" and "stream" exist in your resulting GeoDataFrame (as should). But also some other attributes, such as "brook", "proposed" etc are there, and you are wondering why? 

The reason why these "extra" rows seems to be *leaking* to your result is because those tags ("brook" etc), were not listed in your `waterways_exclude` list. Hence, they were not filtered out (which is how the filter with "exclude" should work). And because OpenStreetMap basically allows to tag a feature with any sort of attribute information, it is impossible to keep a "perfect" list of all the tag values that should be excluded. Hence, the list that you get from `osm.conf.tags.waterway` can be seen only as a good reference point for *typical* values that are tagged as "waterway" (but not exhaustive). That list is based on OSM wiki page for "waterways": https://wiki.openstreetmap.org/wiki/Key:waterway

So indeed if you wish to only **keep** specific tags from the data, you should use `filter_type="keep"`. That is the safest way to keep only specific rows that you are interested in.

Did this help you to understand what is going on here?

Best,
Henrikki

**Comment by HTenkanen** [comment]
Going through the "waterways" tags now, I saw that "fish_pass" was actually missing from the list (which is listed in the OSM key:waterways). Updated that now. Thanks! 👍

**Comment by der-karl** [comment]
Hey @HTenkanen , thanks for your excellent answer, it solved this problem. 

And thanks for your suggestions on using `filter_type='keep'` instead of `filter_type='exclude'`.  In fact, I prefer using `filter_type='keep'`, because it is faster than the latter (at least for this case). The reason why I wanted to try `filter_type='exclude'` is because I got `polygon` geometry type in my filtered ways. So I tried the different `filter_type` to see if the results are the same. I opened a **new issue** for that: https://github.com/HTenkanen/pyrosm/issues/67#issue-733936546
