### ISSUE TITLE
Graphs: When using bounding box, filter nodes as well

### ISSUE THREAD

**Issue by HTenkanen** [HTenkanen/pyrosm#78]

**Comment by bramson** [comment]
I think I ran into the problem that this issue is supposed to fix.
When I run 
```
thisAreaData = pyrosm.OSM('../Data/OSMData/kanto-latest.osm.pbf', bounding_box=boundingPolygon)
nodes, edges = thisAreaData.get_network(nodes=True, network_type="walking")
ax = edges.plot(figsize=(20,20), color="gray")
ax = nodes.plot(ax=ax, color="red", markersize=2.5)
```
I get the edges and nodes for Shibuya as expected, but the nodes are not limited to the bounding polygon as seen in the attached plot.

![walkNetwork-pyrosm-ShibuyaKu-v2](https://user-images.githubusercontent.com/16698232/98917463-c1bc1c80-250f-11eb-987a-aa3b2559a182.png)

**Comment by HTenkanen** [comment]
@bramson Yes, this is something that still needs a few extra lines of code 👍 I aim to fix this today.

**Comment by HTenkanen** [comment]
@bramson Okay, now this works as should:
![image](https://user-images.githubusercontent.com/6659534/98922527-3cb71000-24db-11eb-9f52-d8441762eac6.png)

You should get this working by updating the library again from the master branch 👍 

By the way, I remember you mentioning something about constructing the bounding box geometry. As you can see above, it is possible to also just pass a list of coordinates for the bounding_box parameter (that might be easier sometimes). It follows format: `[minx, miny, maxx, maxy]`.

I have sometimes used this online tool to find bounding box coordinates which is quite handy:
https://boundingbox.klokantech.com/
